config/routes.rb
Rails.application.routes.draw do
  get '/users/home' => 'users#home', as: "user_home"
  get '/users/:id/my_likes' => 'recipes#my_likes', as: "my_likes"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#home'
  patch '/users/:user_id/pantry' => 'pantries#update', as: 'user_pantry_update'
  post '/recipes/:recipe_id/comments' => 'comments#create', as: "create_recipe_comment"
  resources :users do
    resource :pantry
    resources :recipes
  end
  resources :recipes, only: [:update, :create, :show, :destroy, :index]
  get '/recipes/search' => 'recipes#search', as: "search"
  resources :comments, only: [:destroy, :update]
  get '/recipes/:id/missing_ingredients/:user_id' => 'recipes#missing_ingredients'
  resources :pantry_ingredients
  resources :ingredients
  resources :recipe_ingredients
  resources :categories
  resources :users
  resources :likes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  #scope in some ways appears to be a code style thing
  #I have elected to have all my methods that deal with AR
  #queries be scopes


  scope :by_ingredients, -> (ingredient_ids) { joins(:recipe_ingredients).where(recipe_ingredients: {ingredient_id: ingredient_ids}).distinct }

  #works in console, significant changes would need to be made to index action unless we use javascript. Come back to this one.
  scope :ingredient_names, -> (names) { joins(:ingredients).where(ingredients: {name: names}).distinct }
  scope :most_recent, -> {order('created_at DESC')}
  scope :by_categories, -> (meal_category) {joins(:categories).where(categories: {name: meal_category})}
  scope :by_likes, -> { order('likes_count DESC') }
  scope :is_liked, ->(enabled) {Recipe.select('recipes.*').joins(:likes).group('recipes.id').having('count(likes.id) > 0') if enabled}
  scope :search_query, -> (query) {Recipe.where("lower(title) like ?", "%#{query.downcase}%")}

  attr_accessor :food_hash
  MAX_CARBS = 20
  SILLY_AMOUNT = 100
  DEFAULT_IMAGE = "https://i.imgur.com/D4OUBUs.jpg"
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments
  has_many :recipe_categories
  has_many :categories, through: :recipe_categories
  has_many :likes
  has_many :liking_users, through: :likes, source: :user
  before_save :url_checker
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :title, length: {maximum: 40}
  validates :servings, presence: true
  validates :servings, numericality: {less_than_or_equal_to: 60}
  validates :servings, numericality: {greater_than_or_equal_to: 1, only_integer: true}
  validates :description, presence: true
  validates :ingredient_list, presence: true
  validate :analyze_ingredients
  validate :keto_friendly

  def self.my_likes(user_id)
    likes = Like.user_likes(user_id)
    recipe_ids = likes.pluck(:recipe_id)
    Recipe.all.where(id: recipe_ids)
  end

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category|
      next if category.values.first.empty?
      category = Category.find_or_create_by(category)
      category.recipes << self unless category.recipes.include?(self)
    end
  end

  def categories_names
    categories.collect {|category|category.name}
  end

  def url_checker
      self.image = DEFAULT_IMAGE if self.image.nil? || self.image.empty?
  end

  def self.my_pantry(user)
    recipes =  by_ingredients([user.pantry_ids])
    recipes = recipes.sort_by {|recipe| recipe.missing_ingredients(user).size}
    recipes.delete_if {|recipe| recipe.missing_ingredients(user).size > 7}
  end

  def analyze_ingredients

    #is this a code smell??? I don't know. But it is the best way I can seem to handle validation using the API
    if ingredient_list
      wrapper = EdamamWrapper.new
      food_hash = wrapper.line_ingredient_parser(ingredient_list)
      self.food_hash = food_hash
      if food_hash.class == String
        errors.add(:ingredients, "#{food_hash}")
      else
        add_nutrition
      end
    end
  end

  def missing_ingredients(user)
    ingredients - user.pantry_ingredients
  end

  def missing_ingredient_names(user)
    ingredients = missing_ingredients(user)
    ingredients = ingredients.collect {|ingredient|ingredient.name}
    "To make this recipe, you will need: #{ingredients.to_sentence}"
  end

  def update_food
    ingredients.clear
    save_food
  end

  def save_food
    food_hash[:ingredients].each do |ingredient, values|
      new_ingredient = Ingredient.find_or_create_by_food_id(values[:food_id], ingredient)
      RecipeIngredient.create(recipe: self, ingredient: new_ingredient, quantity: values[:quantity], measure: values[:measure] )
    end
  end

  private

  def keto_friendly
    if self.errors.none?
      net_carb_serving = (self.carbs - self.fiber) / self.servings
      if net_carb_serving > SILLY_AMOUNT
        puts net_carb_serving
        errors.add(:ingredients, "That recipe is definitely NOT keto friendly!")
      elsif net_carb_serving > MAX_CARBS
        puts net_carb_serving
        errors.add(:ingredients, "There are too many net carbs per serving")
      end
    end
  end

  def add_nutrition
    food_hash[:nutrients].each do |label, amount|
        self.send("#{label}=", amount)
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    before_action :recipe_setter, only: [:show, :edit, :update, :destroy]
    before_action :require_login, only: [:show, :edit, :new, :create, :update, :destroy]
    before_action :has_pantry, only: [:show]

    def index
        if params[:user_id]
            @recipes = User.find(params[:user_id]).recipes
        else
            @recipes = Recipe.where(nil)
            filtering_params(params).each do |key, value|
                if value == "true"
                    @recipes = @recipes.public_send(key, current_user)
                elsif value.present?
                    @recipes = @recipes.public_send(key, value)
                end
            end
        end
        render json: @recipes if params[:request] || request.format.symbol == :json
    end

    def my_likes
        @recipes = Recipe.my_likes(params[:id])
        render :server_index
    end

    def show
        @like = current_user.likes_recipe(@recipe) || Like.new(user: current_user, recipe: @recipe)
        @comment = Comment.new(user: current_user, recipe: @recipe)
        @comments = @recipe.comments

        respond_to do |format|
            format.html {render :show}
            format.json {render json: @recipe}
        end

    end

    def new
        @recipe = Recipe.new(user: current_user)
        @category = @recipe.categories.build
    end

    def create
        @recipe = Recipe.new(user: current_user)
        @recipe.assign_attributes(recipe_params)
        if @recipe.save
            @recipe.save_food
            flash[:notice] = "#{@recipe.title} successfully created!"
            redirect_to user_recipe_path(@recipe.user, @recipe)
        else
            @category = @recipe.categories.build
            render :new
        end
    end

    def edit
       @category = @recipe.categories.build
    end

    def update
        authorize @recipe
        if @recipe.update(recipe_params)
            @recipe.update_food
            flash[:notice] = "#{@recipe.title} successfully updated!"
            redirect_to user_recipe_path(@recipe.user, @recipe)
        else
            @category = @recipe.categories.build
            render :edit
        end
    end


    def destroy
        authorize @recipe
        @recipe.recipe_categories.destroy_all
        @recipe.destroy
        flash[:notice] = "#{@recipe.title} successfully deleted"
        redirect_to user_recipes_path(current_user)
    end

    def search
    end

    def missing_ingredients
        user = User.find(params[:user_id])
        @recipe = Recipe.find(params[:id])
        #that won't work, treat as psuedo code
        names = @recipe.missing_ingredient_names(user)
        count = @recipe.missing_ingredients(user).size
        @missing_ingredients = {missing_names: names, missing_count: count}
        render json: @missing_ingredients
    end

    private

    def filtering_params(params)
        params.slice(:by_ingredients, :most_recent, :by_categories,
        :by_likes, :is_liked, :search_query, :my_pantry, :my_likes)
    end

    def recipe_params
       params.require(:recipe).permit(:title, :image, :description, :serving_size,
       :ingredient_list, :cook_time, :prep_time, :servings, :user_id,
       :categories_attributes => [:name], :category_ids => [])
    end

    def recipe_setter
        @recipe = Recipe.find(params[:id])
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper

    def top_recipes(meal_category, limit=3)
       @recipes = Recipe.by_categories(meal_category).by_likes.first(limit)
    end

    def like_button
        #figure out why the eff this doesn't work, but directly embedding it does
        if current_user.liked_recipes.include?(@recipe)

            form_for(@like, method: :delete) do |f|
                #future javascripty-front-endy-me: have icon show liked, then on hover change it to unlike
                #also AJAX the heck out if it so that the page doesn't reload
                f.submit "Unlike", class: 'btn btn-primary'
            end

        else 

            form_for(@like) do |f|
                f.hidden_field :recipe_id, value: "#{@recipe.id}"
                f.submit "Like", class: 'btn btn-primary'
            end

        end

    end

end

app/views/recipes/_Oldrecipe.html.erb
<div class="col-md-4">
    <div class="card" >
        <!-- <img class="card-img-top" src=<%=recipe.image%> style="width: 100%" alt="Card image cap"> -->
<div class="thumbnail">
 <div class="img-wrapper">
                <%= link_to user_recipe_path(recipe.user, recipe) do%>
                    <%= image_tag "#{recipe.image}", style: "width:100%", class: "card-img-top"%>
                <%end%>
 </div>
         <div class="card-block">
            <br>
            <%= link_to user_recipe_path(recipe.user, recipe) do%>
                <h6 class="card-title"><%=recipe.title%></h6>
            <% end %>
            <h7 class="card-title"><%=recipe.comments.size%> comments </h7>
        </div>
</div>

    </div>
</div>

app/views/recipes/_jsindex.js.erb
function init(){
    class RecipeCard{
        constructor(recipe){
            this.title = recipe.title;
            this.image = recipe.image;
            this.commentCount = recipe.comments.length;
            this.recipeURL = "/users/" + recipe.user.id + "/recipes/" + recipe.id;
        }

        cardBuilder(){
            var recipeCard = document.createElement("div")
            
            recipeCard.className ="col-md-4"
            recipeCard.innerHTML = "<%=j render(partial: 'recipe_card_template')%>";
            recipeCard.getElementsByClassName("recipePath")[0].href = this.recipeURL
            recipeCard.getElementsByClassName("recipePath")[1].href = this.recipeURL
            recipeCard.getElementsByClassName("recipeImage")[0].src = this.image
            recipeCard.getElementsByClassName("card-title")[0].innerHTML = this.title
            recipeCard.getElementsByClassName("recipeCommentCount")[0].innerHTML = this.commentCount + ' comments'
            document.getElementsByClassName("row")[0].appendChild(recipeCard)
        }

    }

    function clearRecipeCache(){
        document.getElementsByClassName("row")[0].innerHTML = "";
    }

    function requestRecipes(){
        //rails renders empty page which has AJAX request attached to it which calls the same URL with a JSON request
        let path = window.location.href.replace(/https?:\/\/localhost:3000/, "")
        if(path.includes("commit")){
            path = path + "&request=true"
        }
        else {
            path = path + ".json"
        }

        $.get(path, function(recipes){
            clearRecipeCache()
            for (const recipe of recipes) {
                let card = new RecipeCard(recipe);
                card.cardBuilder()
            }
        })
    }

    $(function(){
        requestRecipes()
    });
}
init()

app/views/recipes/_recipe.html.erb
<div class="col-md-4">
    <div class="card" >
        <!-- <img class="card-img-top" src=<%=recipe.image%> style="width: 100%" alt="Card image cap"> -->
<div class="thumbnail">
 <div class="img-wrapper">
                <%= link_to user_recipe_path(recipe.user, recipe) do%>
                    <%= image_tag "#{recipe.image}", style: "width:100%", class: "card-img-top"%>
                <%end%>
 </div>
         <div class="card-block">
            <br>
            <%= link_to user_recipe_path(recipe.user, recipe) do%>
                <h6 class="card-title"><%=recipe.title%></h6>
            <% end %>
            <h7 class="card-title"><%=recipe.comments.size%> comments </h7>
        </div>
</div>

    </div>
</div>

app/views/recipes/_recipe_card_template.html.erb
<div class="card" >
<div class="thumbnail">
 <div class="img-wrapper">
                <%= link_to "#", class:"recipePath" do%>
                    <%= image_tag "" , style: "width:100%", class: "card-img-top recipeImage" %>
                <%end%>
 </div>
         <div class="card-block">
            <br>
            <%= link_to "#", class:"recipePath" do%>
                 <h6 class="card-title"> <!-- recipe title here --> </h6> 
            <% end %>
            <h7 class="card-title recipeCommentCount"><!-- recipe comment count here --> comments </h7>
        </div>
</div>

    </div>

app/views/recipes/_recipe_form.html.erb
<% image_url = nil if recipe.image == "https://i.imgur.com/D4OUBUs.jpg" %>
<%= form_for recipe do |f| %>
    <% if recipe.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

            <ul>
                <% recipe.errors.full_messages.each do |msg| %>
                    <li>
                        <%= msg %>
                    </li>
                    <% end %>
            </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:"form-control", placeholder: "Enter a catchy name" %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
            <%= f.text_field :image, class:"form-control", value: image_url, placeholder: "Enter a URL to a picture of your tasty food (optional)"%>
    </div>
        <div class="row">
            <div class="col-4">
                <%= f.label :prep_time%>
                <%= f.text_field :prep_time, class: "form-control", placeholder: "Enter hours and minutes" %> <br>
            </div class="col-4">
            <div class="col-4">
                <%= f.label :cook_time%>
                <%= f.text_field :cook_time, class: "form-control", placeholder: "Enter hours and minutes"%>
            </div>
            <div class="col-4">
                <%= f.label :servings%>
                <%= f.number_field :servings, class: "form-control" %>
            </div>
        </div>

    <div class="form-group">
        <%= f.label :ingredient_list, "Ingredients"%>
        <%= f.text_area :ingredient_list, class: "form-control", placeholder:"Please enter ingredients one line at a time", rows: "10" %> <br>
        <%= f.label :description, "Recipe Instructions"%>
        <%= f.text_area :description, class: "form-control", placeholder: "Enter a description of how to make your recipe", rows: "10" %>
    </div>

    <div class="form-group" >
        <%= f.label :category_ids, "Choose recipe categories:"%>
        <!-- TURN THIS INTO A DROP DOWN WITH MULTIPLE SELECT USING THE JQUERY GEM -->
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
    
        <br>
        <%if policy(@category).create?%>
            <%=f.fields_for :categories do |category_attribute| %>
                <% next unless category_attribute.object.persisted? %>
                <br>
                <%= category_attribute.label :name, "Create Category"%>
                <br>
                <%= category_attribute.text_field :name, value: nil, placeholder:"Enter new category name"%>
            <%end%>
        <%end%>
    </div>

    <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/recipes/edit.html.erb
<br>
<div class="container content-box">
    <h1>Edit <%=@recipe.title%></h1>
    <br>
    <%= render partial: "recipe_form", locals: {recipe: @recipe} %>
        <br>
</div>
<br>

app/views/recipes/index.html.erb
<div class="container">
        <br>
        <div class="row">
           
        </div>
    <br>
</div>

<!-- loading scripts here -->

<script>
    <%= render partial: "jsindex",formats:[:js]%>
</script>

app/views/recipes/new.html.erb
<br>
<div class="container content-box">
    <h1>New Recipe</h1>
    <br>
        <%= render partial: "recipe_form", locals: {recipe: @recipe} %>
    <br>
</div>
<br>

app/views/recipes/search.html.erb
<br>

<div class="container">
    <div class="row justify-content-center content-box">
    <div class="col-md-8">
        <h2>Advanced Search</h2>
        <br>
        <%= form_tag(recipes_path, method: :get) do %>
        <div class="row">
          <div class="col-8">
            <%= text_field_tag :search_query, "", class: "form-control", placeholder: "Recipe Name" %>
          </div>
          <div class="col-4">
               <%= check_box_tag("is_liked", true, false, class:"checkbox-inline")  %>
              <%=h 'Display only liked recipes' %>
          </div>
        </div>
        <br>
          <%= label_tag "Order by:"%>
          <br>
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-primary"><%= radio_button_tag :order, "by_likes" %> Likes</label>
            <label class="btn btn-primary"><%= radio_button_tag :order, "most_recent" %> Most recent</label>
          </div>
          <br>
          <%= label_tag "Choose Recipe Categories:"%>
          <br>
          <div class="btn-group" data-toggle="buttons">
            <% Category.all.each do |category| %>
              <!-- using names instead of ids is desired for better URL clarity -->
              <br>
                <label class='btn btn-primary'>
                  <%= check_box_tag("by_categories[]", category.name, false, class:"checkbox")  %> <%=category.name%>
                </label>
            <% end %>
            <br>
          </div>
          <p>&nbsp</p>
          <div class=><%= submit_tag 'Search', class: "btn btn-primary" %></div class="row">
        <% end %>
    </div>
    
    </div>
  </div>
</div>

app/views/recipes/server_index.html.erb
<div class="container">
        <br>
    <% if !@recipes.empty? %>
        <div class="row">
            <%= render(@recipes)%>
        </div>
    <% else %>
        <div class="row justify-content-center">
            <div class="col-md-10 content-box" style="text-align:center;">
                <h4>There are no recipes here. Create one!</h4>
                <br>
                <%= button_to  "New Recipe", new_user_recipe_path(current_user), class:"btn btn-primary", method: :get %>
            </div>
        </div>
    <% end %>
    <br>
</div>

app/views/recipes/show.html.erb
<br>

    <div class="container">

        <div class='row justify-content-center' >
            <div class="col-md-10 content-box">
                
                <div class="container">
                    <div class="row">
                        <div class="col-10">
                            <h2 id="recipeTitle"></h2>
                        </div>
                        <% if policy(@recipe).update?%>
                            <div id="adminFeatures" class="btn-group col-2">
                                <%= button_to  "Edit", "", method: :get, class: "btn btn-primary"  %>
                                <%= button_to  "Delete", "", method: :delete, class: "btn btn-secondary" %>                          
                            </div>
                        <% else %>
                            <div id="adminFeatures" class="btn-group col-2", style="visibility:hidden">
                                <%= button_to  "Edit", edit_user_recipe_path(@recipe), method: :get, class: "btn btn-primary"  %>
                                <%= button_to  "Delete", user_recipe_path(@recipe), method: :delete, class: "btn btn-secondary" %>                          
                            </div>
                        <% end %>

                    </div>
                    <div class="container">
                        <br>
                        <%= image_tag  "", style: "width:100%;", id:"recipePicture" %>
                        <br>
                    </div>
                    <br>
                    <div class="container">
                        <% if @like.persisted? %>
                            <%= form_for(@like, method: :delete) do |f| %>
                                <%= f.submit "Unlike", class: 'btn btn-primary', id:"likeButton" %>
                            <% end %>
                            <% else %>
                                <%= form_for(@like) do |f| %>
                                <%= f.hidden_field :recipe_id, value: "#{@recipe.id}" %>
                                <%= f.submit "Like", class: 'btn btn-primary', id:"likeButton" %>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                    <h3>Macronutrients per Serving</h3>
                    <h4 id="recipeServings"></h4>
                    <ul>
                        <li id="recipeCalories"></li>
                        <li id="recipeFat"></li>
                        <li id="recipeProtein"></li>
                        <li id="recipeCarbs"></li>
                        <li id="recipeFiber"></li>
                    </ul>
                    <hr>
                </div>
            </div>
            <div class="col-md-10 content-box">
                <div class="container">
                    <h3>Categories</h3>
                    <p id="recipeCategories" ></p>
                    <hr>
                </div>
            </div>
            <div class="col-md-10 content-box">
                <div class="container">
                    <h3>Ingredients</h3>
                    <ul id="recipeIngredients">
                        <br>
                    </ul>
                    <hr>
                </div>
            </div>

            <div class="col-md-10 content-box">
                <div class="container">
                    <h3>Directions</h3>
                    <br>
                    <div id="recipeDescription">
                    </div>
                </div>
            </div>

    <%if @recipe.missing_ingredients(current_user) %>
        <div class="col-md-10 content-box">
            <div class="container">
                <!-- Shows the ingredients that the user is missing -->
                <!--To get this working, we can make a POST route /missing_ingredients,
                takes the current user ID and the recipe ID. It will return a list of missing ingredients. -->
                <h4 id="missingCount"></h4>
                <p>
                    <br>
                    <div id="missingIngredients"></div>
                    <hr>
                </p>
            </div>
        </div>
    <%end%>
    <br>
    <div class="col-md-10 content-box">
        <div class="container">
        	<!-- these are all the comments -->
            <div class="row">
            	<div class="col-10">
            		<h4 style="display: inline;">Comments</h4>
                </div>
                <div class="col-2">
                    <button type="button" data-toggle="modal" id="postComment" data-target="#leaveComment" style="display: inline;" class="btn btn-primary pull-right">Post a Comment</button>
                </div>
            </div>
        <div id="commentsBox">
        </div>
        </div>
        <br>
        
        </div>
                
            <div class="col-md-10">
                <div class="container">
                    <br>
                    <div class="row justify-content-center">
                        <div class="col-md-1 mr-auto">
                            <%= link_to  material_icon.navigate_before.md_36, "", id: "prevRecipe"%>
                        </div>
                        <div class="col-md-4 mx-auto text-center">
                            <h5>View more
                                <%=@recipe.categories.first.name%> recipes</h5>
                        </div>
                        <div class="ml-auto col-md-1">
                            <%= link_to  material_icon.navigate_next.md_36, "", id: "nextRecipe"%>
                        </div>
                    </div>
                </div>
            </div>
    </div>

    </div>
   
    <br>
<!-- Create new comment area-->

<%=bootstrap_modal("leaveComment"){ form_for @comment, url: create_recipe_comment_path(@recipe) do |f| %>
    <%= f.label :content, "New Comment"%> <br>
    <%= f.text_area :content, class:"form-control", rows: 3 %> <br>
    <%= f.submit id: "newCommentSubmit"%>
<% end }%>

<!-- edit comment here -->

<%= render partial: "comments/edit_comment" %>

<!-- loading view scripts here -->

<script>
    <%= render partial: "jsrecipe",
        formats: [:js]
    %>
</script>