config/routes.rb
Rails.application.routes.draw do
  get '/users/home' => 'users#home', as: "user_home"
  get '/users/:id/my_likes' => 'recipes#my_likes', as: "my_likes"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#home'
  patch '/users/:user_id/pantry' => 'pantries#update', as: 'user_pantry_update'
  post '/recipes/:recipe_id/comments' => 'comments#create', as: "create_recipe_comment"
  resources :users do
    resource :pantry
    resources :recipes
  end
  resources :recipes, only: [:update, :create, :show, :destroy, :index]
  get '/recipes/search' => 'recipes#search', as: "search"
  resources :comments, only: [:destroy, :update]
  get '/recipes/:id/missing_ingredients/:user_id' => 'recipes#missing_ingredients'
  resources :pantry_ingredients
  resources :ingredients
  resources :recipe_ingredients
  resources :categories
  resources :users
  resources :likes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pantry.rb
class Pantry < ApplicationRecord
  attr_accessor :no_food_id
  attr_accessor :not_unique
  belongs_to :user
  has_many :pantry_ingredients
  has_many :ingredients, through: :pantry_ingredients
  validate :has_food_id
  validate :is_unique_ingredient



  def ingredients_attributes=(ingredient)
    ingredient.values.each do |food_item|
      food_name = food_item[:name]
      wrapper = EdamamWrapper.new
      food_response = wrapper.ingredient_finder(food_name)
      begin
        food_id =  food_response.body["ingredients"][0]["parsed"][0]["foodId"]
        ingredient = Ingredient.find_or_create_by_food_id(food_id,food_name)
        pantry_ingredient = PantryIngredient.new(pantry_id: self.id, ingredient_id: ingredient.id)
        if pantry_ingredient.save
          self.save
        else
          self.not_unique = true
        end
      rescue
        self.no_food_id = food_name
      end
    end

  end

  def ingredient_ids
    ingredients.collect{|ingredient| ingredient.id}
  end

  private

  def is_unique_ingredient
    if not_unique
      errors.add(:ingredients, "That food is already in your pantry!")
    end
  end

  def has_food_id
    if no_food_id
      errors.add(:ingredients, "#{no_food_id} does not appear to be a valid food")
    end
  end

end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController

  before_action :require_login
  before_action :pantry_setter, only: [:show, :edit, :update]

  def show
  end

  def edit
    @pantry.ingredients.build
  end

  def update
    if  @pantry.update(pantry_params)
      redirect_to user_pantry_path(@user)
    else
      @pantry.ingredients.build
      render :edit
    end
  end

  def delete
  end

  private

  def pantry_setter
     @user = current_user
     @pantry = @user.pantry
     @pantry = Pantry.create(user: @user) if @pantry.nil?
  end

  def pantry_params
    params.require(:pantry).permit(ingredients_attributes: [
      :name
    ])
  end

end

app/helpers/pantries_helper.rb
module PantriesHelper
end

app/views/pantries/_new_ingredient.html.erb
<div class="container content-box">
<h2>Add to pantry</h2>
<hr>
<div class="container">
  <%= form_for @pantry, url: user_pantry_update_path do |f| %>
  <% if @pantry.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pantry.errors.count, "error") %> prohibited your pantry from being updated:</h2>
  
      <ul>
        <% @pantry.errors.values.each do |msg| %>
          <li>
            <%= msg.first %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
    <%= f.fields_for :ingredients do |t| %>
    <% next unless t.object.id.nil? #only shows new pantry ingredients %> 
    <div><p>Ingredient Name<%= t.text_field :name, class: "form-control" %></p></div>
    <%end%>
  <%= f.submit "Find Ingredient", class: "btn btn-primary"%>
  <% end %>
</div>
</div>

app/views/pantries/_pantry.html.erb
<div class="container">
  <%if @pantry.ingredients.empty?%>
  <p>There are no ingredients in your pantry!</p>
  <%end%>
  <%@pantry.pantry_ingredients.each do |pantry_ingredient|%>
    <div class="row">
      <div class="col-10">
        <%= link_to pantry_ingredient.ingredient, class: "no-color" do %>
          <h4><%= pantry_ingredient.ingredient_name.capitalize%></h4>
        <% end %> 
      </div>
      <div class="col-2">
        <%= button_to "Remove from pantry", pantry_ingredient, method: :delete, class: 'btn btn-secondary btn-sm' %>
      </div>
    </div>
      <hr>
  <%end%>
</div>

app/views/pantries/edit.html.erb
<div class="container">
    <br>
    <%= render partial: "new_ingredient", locals: {pantry: @pantry} %>
</div class="container">

app/views/pantries/show.html.erb
<div class="container">
    <br>
<div class="container content-box">
    <h1>My Pantry</h1>
    <br>
    <div class="btn-group">
        <%= link_to  "Add Ingredient", edit_user_pantry_path, class: 'btn btn-primary' %>
        <%= form_tag( recipes_path , method: :get) do %>
            <%= hidden_field_tag :my_pantry, "true" %>
            <%= submit_tag "What can I make tonight?", class: 'btn btn-secondary'%>
        <% end %>
    </div>
</div>
    
<div class="content-box">
        <%= render(@pantry) %>
        <!-- make a list of all pantry items -->
        <br>
</div>

</div class="container">
<br>