config/routes.rb
Rails.application.routes.draw do
  get '/users/home' => 'users#home', as: "user_home"
  get '/users/:id/my_likes' => 'recipes#my_likes', as: "my_likes"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#home'
  patch '/users/:user_id/pantry' => 'pantries#update', as: 'user_pantry_update'
  post '/recipes/:recipe_id/comments' => 'comments#create', as: "create_recipe_comment"
  resources :users do
    resource :pantry
    resources :recipes
  end
  resources :recipes, only: [:update, :create, :show, :destroy, :index]
  get '/recipes/search' => 'recipes#search', as: "search"
  resources :comments, only: [:destroy, :update]
  get '/recipes/:id/missing_ingredients/:user_id' => 'recipes#missing_ingredients'
  resources :pantry_ingredients
  resources :ingredients
  resources :recipe_ingredients
  resources :categories
  resources :users
  resources :likes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<%if flash[:notice] %>
<div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%=flash[:notice]%></p>
</div>
<%end%>

<%if flash[:alert] %>
    <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%= flash[:alert] %></p>
    </div>
<% end %>

<%if flash[:error]%>
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p><%=flash[:error]%></p>
    </div>
<%end%>

app/views/layouts/_footer.html.erb
<nav class="navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/f3mshep">
                        <%= fa_icon "github", style: "font-size: 40px;"%>
                    </a>
                </li>
                <li class="nav-link">
                    <a class="no-color nav-link" href="https://developer.edamam.com/">
                        <p style="font-size: 13px;">Recipe analysis powered by Edamam API</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<div class="container">
    <a class="navbar-brand pull-lg-right" href="/">Keto Tonight</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <%if !current_user %>
          <ul class= "navbar-nav mr-auto">
            <li class="nav-item" ><%= link_to  "Sign in", new_user_session_path, class:'nav-link' %></li>
            <li class="nav-item" ><%= link_to  "Sign up", new_user_registration_path, class: 'nav-link' %></li>
          </ul>
        <% else %>
        <div class="navbar-nav mr-auto">
            <li class="nav-item" ><%= link_to  "Breakfast", category_path(breakfast_category), class: "nav-link" %></li>
            <li class="nav-item" ><%= link_to  "Lunch", category_path(lunch_category), class: "nav-link" %></li>
            <li class="nav-item" ><%= link_to  "Dinner", category_path(dinner_category), class: "nav-link" %></li>
        </div>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item" ><%= link_to  material_icon.search.md_36, search_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <%= material_icon.account_circle.md_36%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to("Likes", my_likes_path(current_user.id) , class: 'dropdown-item') %>
              <%= link_to  "New recipe", new_user_recipe_path(current_user), class: 'dropdown-item' %>
              <%= link_to  "My Recipes", user_recipes_path(current_user), class: 'dropdown-item' %>
              <%= link_to  "Pantry", user_pantry_path(current_user), class: 'dropdown-item' %>
              <%= link_to  "Sign out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <% if current_user.admin%>
                <%= link_to  "Category management", categories_path, class: 'dropdown-item' %>
              <% end%>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KetoTonight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

<%if current_page?('/')%>
<body>
  <%= stylesheet_link_tag    'static', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield %>
</body>
<%else%>
  <body>
    <div class="page-wrap">
      <%= render "layouts/flash" %>
      <%= render "layouts/navbar" %>
      <%= yield %>
    </div class="page-wrap">
    <div class="footer-wrap">
      <footer>
        <%= render  "layouts/footer" %>
      </footer>
    </div>
  </body>

<%end%>

</html>